version: '3.1'

services:
  web:
    image: nginx:latest
    ports:
      - "60080:80"
    volumes:
      - wordpress:/code
      - ./site.conf:/etc/nginx/conf.d/default.conf
    links:
      - wp
  wp:
    image: wordpress:php7.4-fpm-alpine
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
  cli:
    depends_on:
      - db
      - wp
    image: wordpress:cli
    # vstm: This is required to run wordpress-cli with the same
    # user-id as wordpress. This way there are no permission problems
    # when running the cli
    user: xfs
    # vstm: The sleep 10 is required so that the command is run after
    # mysql is initialized. Depending on your machine this might take
    # longer or it can go faster.
    # vstm: add shared volume
    volumes:
      - wordpress:/var/www/html
volumes:
  wordpress:
  db:
